### ISSUE TITLE
Problem mask with devices android in chrome

### ISSUE THREAD

**Issue by Juliojss** [cesarrew/ng2-currency-mask#134] opened 2019-08-27 14:20 UTC
I encountered a problem with masking on android devices in chrome 76. When erasing the value, it does not add the mask again. An alternative was to apply nullable false to mask settings.

**Comment by ivofernandes** [comment] 2020-09-02 10:33
The problem is with the event target isn't?

**Comment by ivofernandes** [comment] 2020-09-02 10:39
Check if this fixes your bug :)
https://github.com/cesarrew/ng2-currency-mask/pull/150

**Comment by cesarrew** [comment] 2021-12-23 14:05
Fixed in version 13.0.3.

**Closed by cesarrew** 2021-12-23 14:05 UTC
